[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
gfx_task = "Gw5zhyN2zL7Y3PjKAT2bcbPmk9LdPjkqBxtpXPfAKyLE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/un/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
